#!/bin/bash

# set yadm class
yadm config local.class Minimal

# specify preferred text editor
PREFERRED_EDITOR="vscode"

# whether to install Homebrew
USE_HOMEBREW="true"

# whether to install Conda
USE_CONDA="false"

# whether user who will be using this profile has admin (sudo) privileges
USER_ADMIN_PRIVILEGE="true"
