#!/bin/bash

# set yadm class
yadm config local.class Personal

# whether to install Homebrew
USE_HOMEBREW="true"

# whether user who will be using this profile has admin (sudo) privileges
USER_ADMIN_PRIVILEGE="true"
