#!/bin/bash

# set yadm class
yadm config local.class sandiego

# specify preferred text editor
PREFERRED_EDITOR="vscode"

# whether to install Homebrew
USE_HOMEBREW="true"

# whether to install Conda
USE_CONDA="false"

# whether user who will be using this profile has admin (sudo) privileges
USER_ADMIN_PRIVILEGE="true"

# name of custom terminal theme to use
# should be named "<theme name>.terminal" and saved in .dotfiles/shell
TERMINAL_THEME_NAME="solarized-dark"
