#!/bin/bash

#
# Customization
#

# set environment variables
. "$HOME/.dotfiles/shell/shell-env"

# set custom aliases
. "$HOME/.dotfiles/shell/shell-aliases"

# custom prompt
. "$HOME/.dotfiles/shell/bash_prompt"

# enable colorized terminal output
if command -v gdircolors >/dev/null; then
    test -r "$HOME/.dotfiles/shell/dircolors" && eval "$(gdircolors -b $HOME/.dotfiles/shell/dircolors)" || eval "$(gdircolors -b)"
fi

# Store multiline commands as one line.
shopt -s cmdhist

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

#
# Set PATH
#

PATH_LOCATIONS=( "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/sbin" "/usr/sbin" "/sbin" )
for x in "${PATH_LOCATIONS[@]}"; do
	if echo $PATH | grep -q $x; then 
		:
	else 
		PATH=$PATH:$x
	fi
done

# add VS Code to PATH to allow launching (using `code`) from the terminal
# (if it's installed and not already in PATH)
if [[ -e "/Applications/Visual Studio Code.app" ]]; then
	if echo $PATH | grep -q "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"; then
		:
	else
		PATH=$PATH:"/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
	fi
fi

# check if X11 is installed; if so, add it to PATH if it's not already
if command -v xdpyinfo >/dev/null; then
	if echo $PATH | grep -q "/opt/X11/bin"; then
		:
	else
		PATH=$PATH:"/opt/X11/bin"
	fi
fi

# check if TeX is installed; if so, add it to PATH if it's not already
if command -v tex >/dev/null; then
	if echo $PATH | grep -q "/Library/TeX/texbin"; then
		:
	else
		PATH=$PATH:"/Library/TeX/texbin"
	fi
fi

# check if conda is installed; if so, add it to PATH if it's not already
if [[ -d $MINICONDA_PATH ]]; then
	for x in "$MINICONDA_PATH/bin" "$MINICONDA_PATH/condabin"; do
		if echo $PATH | grep -q $x; then
			:
		else
			PATH=$PATH:$x
		fi
	done

	# put conda at the front of PATH if we're in a vscode integrated terminal AND 
	# it's not already (so any python installations from a conda environment will 
	# be preferred to the system python)
	if [[ "$TERM_PROGRAM" = "vscode" ]] && ! (echo $PATH | grep -q "^$MINICONDA_PATH/bin"); then
	    PATH="$MINICONDA_PATH/bin:$PATH"
	fi

	# >>> conda init >>>
	# !! Contents within this block are managed by 'conda init' !!
	__conda_setup="$(CONDA_REPORT_ERRORS=false '$MINICONDA_PATH/bin/conda' shell.bash hook 2> /dev/null)"
	if [ $? -eq 0 ]; then
	    \eval "$__conda_setup"
	else
	    if [ -f "$MINICONDA_PATH/etc/profile.d/conda.sh" ]; then
	        . "$MINICONDA_PATH/etc/profile.d/conda.sh"
	        #CONDA_CHANGEPS1=false conda activate base
	    else
	        \export PATH="$MINICONDA_PATH/bin:$PATH"
	    fi
	fi
	unset __conda_setup
	# <<< conda init <<<
fi

#
# Local overrides
#

# run local bashrc if there is one
test -r "$HOME/.dotfiles/shell/bashrc-local" && . "$HOME/.dotfiles/shell/bashrc-local"
