#!/bin/bash

# prompt for install profile
echo "Which kind of setup would you like to do?"
select profile in $(ls $HOME/.yadm/profiles);
do
	# get settings from profile
	. "$HOME/.yadm/profiles/$profile"
	break;;
done

echo "Checking preliminaries..."
# check if Xcode command line tools are installed and install if not
if type xcode-select >&- && xpath=$( xcode-select --print-path ) && test -d "${xpath}" && test -x "${xpath}"; then
	echo "$(tput setaf 2)Xcode command line tools installed and up to date.$(tput setaf 7)"
else
	echo "Installing Xcode command line tools..."
	xcode-select --install
	echo "$(tput setaf 2)Installed.$(tput setaf 7)"
fi

# install/update Homebrew and programs from Brewfile if desired
if [[ "$USE_HOMEBREW" == "true" ]]; then
	. "$HOME/.brew/brew-install.sh"
fi

# install Conda if desired
if [[ "$USE_CONDA" == "true" ]]; then
	. "$HOME/.conda/conda-install.sh"
fi

# install VS Code if not already and apply custom settings
. "$HOME/.vscode-settings/vscode-setup.sh"

# prompt to install any programs that must be manually installed
if [[ -r "$HOME/.installs/manual" ]]; then
	IFS=";"
	echo "$(tput setaf 3)Recommended programs to install (if not installed already):$(tput setaf 7)"
	grep -v "^#" "$HOME/.installs/manual" | while read -r LINE; do 
		read -ra SPLIT_LINE <<<"$LINE"
		PROGRAM_NAME="${SPLIT_LINE[0]}"
		PROGRAM_URL="${SPLIT_LINE[1]}"
		echo -e "\t$PROGRAM_NAME: $PROGRAM_URL"
	done
	unset IFS
	read -n1 -rsp $'Press any key to continue.\n'
fi

# source .macos file to apply system-wide settings and preferences
echo "Would you like to apply custom macOS settings? (Requires password and restart)"
select answer in "Yes" "No"
do
	case $answer in
		Yes )
			. "$HOME/.macos-settings/.macos"
			break;;
		No )
			break;;
	esac
done
